### ISSUE TITLE
会有重复 点击一次增加一次

### ISSUE THREAD

**Issue by zanjs** [qianjiahao/vue-problems-and-solutions#1]
<img width="597" alt="2016-06-11 15 11 03" src="https://cloud.githubusercontent.com/assets/12947276/15983842/c991a3d0-2fe6-11e6-9672-eb0c8fdad9e9.png">

**Comment by qianjiahao** [comment]
问题已修复，感谢测试~
后面会上一个新功能，便于分享内容，欢迎继续测试哈~~
